server:
  port: 8887
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/course?useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mapper:
  mappers: tk.mybatis.common.MyBaseMapper
  not-empty: true
  identity: MYSQL
