version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mysql:
    image: 'mysql:8'
    container_name: 'mysql8'
    command: --default-authentication-plugin=mysql_native_password
    restart: 'always'
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes: 
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
